 // import house images
 import Libro1 from './assets/Libro1.png';
 import Libro2 from './assets/Libro2.png';
 import Libro3 from './assets/Libro3.png';
 import Libro4 from './assets/Libro4.png';
 import Libro5 from './assets/Libro5.png';
 import Libro6 from './assets/Libro6.png';
 import Libro7 from './assets/Libro7.png';
 import Libro8 from './assets/Libro8.png';
 import Libro9 from './assets/Libro9.png';
 import Libro10 from './assets/Libro10.png';
 import Libro11 from './assets/Libro11.png';
 import Libro12 from './assets/Libro12.png';
 import Libro13 from './assets/Libro13.png';
 import Libro14 from './assets/Libro14.png';
 import Libro15 from './assets/Libro15.png';
 import Libro16 from './assets/Libro16.png';
 import Libro17 from './assets/Libro17.png';
 import Libro18 from './assets/Libro18.png';
 import Libro19 from './assets/Libro19.png';
 import Libro20 from './assets/Libro20.png';
 import Libro21 from './assets/Libro21.png';
 import Libro22 from './assets/Libro22.png';
 import Libro23 from './assets/Libro23.png';
 import Libro24 from './assets/Libro24.png';
 import Libro25 from './assets/Libro25.png';
 import Libro26 from './assets/Libro26.png';
  import Libro27 from './assets/Libro27.png';
  import Libro28 from './assets/Libro28.png';
  import Libro29 from './assets/Libro29.png';
  import Libro30 from './assets/Libro30.png';
  import Libro31 from './assets/Libro31.png';
  import Libro32 from './assets/Libro32.png';
  import Libro33 from './assets/Libro33.png';
  import Libro34 from './assets/Libro34.png';
  import Libro35 from './assets/Libro35.png';
  import Libro36 from './assets/Libro36.png';
  import Libro37 from './assets/Libro37.png';
  import Libro38 from './assets/Libro38.png';
  import Libro39 from './assets/Libro39.png';
  import Libro40 from './assets/Libro40.png';
  
 
 export const LibrosData = [
   {
     id: 1,
     Titulo: 'Los inocentes',
     description:
       'Faltan dos semanas para la boda de la teniente Valentina Redondo y Oliver Gordon. En plenos preparativos, los sorprende la noticia de un atentado masivo en el Templo del Agua del famoso balneario cántabro de Puente Viesgo   Las instalaciones del idílico paraíso de agua estaban ocupadas por un grupo de empresarios, y todo apunta a que la masacre ha sido perpetrada con una peligrosísima arma química. Valentina tendrá que cooperar con el ejército y con un equipo de la UCO para resolver el crimen.',
     image: Libro1,
     Author: 'María Oruña',
     Codigo: '978-84-233-6384-1',
     Disponibles: 6,
     Prestados: 3,
     Total: '9',
     year: '13 sep 2023',
     categoria: 'suspenso',
     valoracion: '4',
   },
   {
     id: 2,
     Titulo: 'Las garras del águila',
     description:
       'Mientras existan hombres que no amen a las mujeres… Lisbeth Salander volverá. La nueva novela de la Serie Millennium, el fenómeno literario que ha atrapado a más de 105 millones de lectores, de la mano de Karin Smirnoff, autora revelación de la narrativa sueca. «Ningún escritor, salvo el mismísimo Stieg Larsson, podría haber escrito una novela así.',
     image: Libro2,
     Author: 'Karin Smirnoff',
     Codigo: '978-84-233-6390-2',
     Disponibles: 6,
     Prestados: 3,
     Total: 9,
     year: '30 ago 2023',
     categoria: 'drama',
     valoracion: 4,
   },
   {
     id: 3,
     Titulo: 'No te olvidaré',
     description:
       'Colleen Hoover, un fenómeno imparable. Una novela conmovedora por la autora de Romper el círculo (It Ends with Us). «Con una habilidad especial para la novela de emociones de alto voltaje, Hoover ha vendido más de 20 millones de libros. Y lo ha hecho a su manera',
     image: Libro3,
     Author: 'Colleen Hoover',
     Codigo: '978-84-08-27717-0',
     Disponibles: 6,
     Prestados: 3,
     Total: 9,
     year: '30 ago 2023',
     categoria: 'romance',
     valoracion: 3.5,
   },
   {
     id: 4,
     Titulo: 'No te veré morir',
     description:
       'Durante su juventud, Gabriel Aristu y Adriana Zuber protagonizaron una apasionada historia de amor que parecía destinada a durar para siempre. El futuro, sin embargo, tenía otros planes para ellos. Separados durante cincuenta años por un océano de incomunicación, ella atrapada en la España de la dictadura, él viviendo el éxito profesional en Estados Unidos, vuelven a encontrarse en el ocaso de sus días. Miradas, caricias, deseos acallados y viejos reproches dejarán paso entonces a la constatación de que la nostalgia de aquel primer amor lo es también de la persona que una vez fuimos.',
     image: Libro4,
     Author: 'Antonio Muñoz Molina',
     Codigo: '0010329199',
     Disponibles: 7,
     Prestados: 2,
     Total: 9,
     year: '30 ago 2023',
     categoria: 'romance',
     valoracion: 2.5,
   },
   {
     id: 5,
     Titulo: 'Bocabesada',
     description:
       'La vida siempre supera al mejor de los guiones una productora de series de televisión que está en un portal que está en una calle que está en uno de los mejores barrios de la ciudad… Por las páginas de Bocabesada aparecen un colaborador televisivo, autor de éxito en crisis; mujeres inteligentes presas de sus errores; puro amor en la tercera edad; directivos mediocres; gente que se muere; un ministro y una puta encantada de serlo.',
     image: Libro5,
     Author: 'Juan del Val',
     Codigo: '978-84-670-6979-2',
     Disponibles: 5,
     Prestados: 1,
     Total: 6,
     year: '27 sep 2023',
     categoria: 'drama',
     valoracion: 1.5,
   },
   {
    id: 6,
     Titulo: 'De amor y de guerra',
     description:
       'En febrero de 1939, la guerra civil española da sus últimas dentelladas. Cuando un bombardeo italiano siega la vida de los padres del joven Román, también mutila su capacidad de amar. Pese a no estar enamorado, se casa con Beatriz, una joven de familia bien con quien tendrá un hijo. Pero todo se trastoca cuando él tiene que huir a Francia. Allí conoce a Teresa, una joven comunista con la que inicia una relación cuajada de secretos.',
     image: Libro6,
     Author: 'Pilar Eyre',
     Codigo: '978-84-08-27668-5',
     Disponibles: 10,
     Prestados: 0,
     Total: 10,
     year: '20 sep 2023',
     categoria: 'drama',
     valoracion: 5,
   },
   {
     id: 7,
     Titulo: 'Todo lo que me ha enseñado el amor',
     description:
       'Tras el éxito de su primer libro, Si tú quieres, te bajas la luna, un viaje hacia el autodescubrimiento a través de la autoestima y el amor propio, Luna Javierre regresa con un libro en el que reflexiona sobre el amor en todas sus formas —la amistad, el amor propio, el amor romántico— y las relaciones sanas. Una preciosa edición con ilustraciones exclusivas de la propia autora.',
     image: Libro7,
     Author: 'Luna Javierre',
     Codigo: '978-84-270-5143-0',
     Disponibles: 2,
     Prestados: 8,
     Total: 10,
     year: '13 sep 2023',
     categoria: 'romance',
     valoracion: 4.5,
   },
   {
     id: 8,
     Titulo: 'Tasmania',
     description:
       'En noviembre de 2015, el narrador, un periodista de formación científica, ha acudido a París para cubrir una cumbre sobre el clima pocos días después de los atentados yihadistas. La crisis que planea en el sombrío ambiente de la ciudad parece un espejo de una crisis más íntima: la que atraviesa la relación que mantiene con su compañera, Lorenza. Y en busca de un sentido a todo lo que está viviendo, a sus miedos y a sus dudas, mientras prepara un libro sobre los efectos radiactivos de la bomba atómica se encuentra con personajes que serán más relevantes de lo que sospecha: un amigo recién separado, un climatólogo experto en nubes, una reportera en zonas de conflicto o un sacerdote que ha encontrado la felicidad donde nunca lo hubiera imaginado.',
     image: Libro8,
     Author: 'Paolo Giordano',
     Codigo: '1234567896',
     Disponibles: 0,
     Prestados: 6,
     Total: 6,
     year: '30 ago 2023',
     categoria: 'suspenso',
     valoracion: 3,
   },
   {
     id: 9,
     Titulo: 'Nos quieren muertos',
     description:
       'En 2014, tras liderar las mayores manifestaciones de protesta en la historia de Venezuela contra el régimen de Nicolas Maduro, el joven político Leopoldo López se vio enfrentado a la decisión más difícil de su vida: o abandonaba su país y seguía la lucha desde el extranjero, o permanecía en Caracas hasta que lo detuvieran. Debía elegir entre la libertad, o la cárcel. Decidió sacrificar su vida familiar y confortable —y entregarse. Al hacer lo que nadie esperaba, se convirtió en héroe.',
     image: Libro9,
     Author: 'Javier Moro',
     Codigo: '978-84-670-6977-8',
     Disponibles: 9,
     Prestados: 4,
     Total: 13,
     year: '20 sep 2023',
     categoria: 'drama',
     valoracion: 2,
     },
   {
     id: 10,
     Titulo: 'Tasmania',
     description:
       'Un viaje extraordinario a través de un apocalipsis contemporáneo y personal.» Vicente Verdú, El País Confronta lo convulso del presente con nuestros conflictos personales más íntimos. Uno de los mejores libros que puedas leer este año.» Isabel Loscertales, Woman',
     image: Libro10,
     Author: 'Paolo Giordano',
     Codigo: '978-84-1107-329-5',
     Disponibles: 6,
     Prestados: 4,
     Total: 10,
     year: '30 ago 2023',
     categoria: 'romance',
     valoracion: 3.5,
   },
   {
     id: 11,
     Titulo: 'Nos quieren muertos',
     description:
       'En 2014, tras liderar las mayores manifestaciones de protesta en la historia de Venezuela contra el régimen de Nicolas Maduro, el joven político Leopoldo López se vio enfrentado a la decisión más difícil de su vida: o abandonaba su país y seguía la lucha desde el extranjero, o permanecía en Caracas hasta que lo detuvieran. Debía elegir entre la libertad, o la cárcel. Decidió sacrificar su vida familiar y confortable —y entregarse. Al hacer lo que nadie esperaba, se convirtió en héroe.',
     image: Libro11,
     Author: 'Javier Moro',
     Codigo: '0010322335',
     Disponibles: 8,
     Prestados: 2,
     Total: '9',
     year: '20 sep 2023',
     categoria: 'accion',
     valoracion: 4.5,
   },
   {
     id: 12,
     Titulo: 'Libelo de sangre',
     description:
       'Durante el crudo invierno de 1620 un espantoso crimen ha sembrado el pánico en cada rincón de Madrid: una joven ha sido violada y enterrada junto a un niño al que le han extirpado el corazón. Nadie en la Villa duda de que se trata de un asesinato ritual, y pronto surge en los mentideros un «libelo de sangre» contra el escribano Sebastián Castro y su esposa, una acusación falsa que culpa a los judíos de sacrificar a menores cristianos para realizar magia negra. Por suerte, Alonso, el hijo mayor del matrimonio, ha conseguido escapar de la Inquisición, encargada de investigar el delito, y de sus horribles métodos; pero ahora deberá enfrentarse a otros peligros no menos terribles: el frío, el hambre y a los miserables que pueblan las calles.',
     image: Libro12,
     Author: 'Sandra Aza',
     Codigo: '0010328801',
     Disponibles: 6,
     Prestados: 3,
     Total: 9,
     year: '6 sep 2023',
     categoria: 'suspenso',
     valoracion: 2.5,
   },
   {
     id: 13,
     Titulo: 'Star War Vader',
     description:
       'La biografía completa de Darth Vader nos cuenta todos los secretos y anécdotas relacionados con el Señor Oscuro, desde su gestación y diseño por parte de George Lucas y su equipo de guionistas. Profusamente ilustrado con fotografías en color de gran tamaño, bocetos y todo tipo de ilustraciones relacionadas con Vader y Star Wars, el libro es un regalo perfecto para fans, nostálgicos y coleccionistas.',
     image: Libro13,
     Author: 'Ryder Widham',
     Codigo: '943-00-233-6384-1',
     Disponibles: 6,
     Prestados: 3,
     Total: '9',
     year: '13 sep 1983',
     categoria: 'accion',
     valoracion: '4',
   },
   {
     id: 14,
     Titulo: 'Carrie',
     description:
       'La historia de Carrie White, una chica de instituto inadaptada, que descubre poco a poco que tiene poderes telequinéticos. Reprimida por una madre dominante y ultrarreligiosa y atormentada por sus compañeros de instituto, sus esfuerzos por encajar la llevan a un dramático enfrentamiento durante el baile de graduación. ',
     image: Libro14,
     Author: 'Stephen King',
     Codigo: '978-84-111-6390-0',
     Disponibles: 6,
     Prestados: 3,
     Total: 9,
     year: '30 ago 1999',
     categoria: 'suspenso',
     valoracion: 4,
   },
   {
     id: 15,
     Titulo: 'It',
     description:
       'La pasaje que has compartido es del libro "It" de Stephen King. Sirve como una introducción a la historia, ofreciendo una visión de los eventos que ocurrieron en el verano de 1958 y el posterior despertar de los personajes en 1985. La historia gira en torno a un grupo de niños conocidos como los Perdedores, que se enfrentaron a horrores inimaginables en su ciudad natal de Derry, Maine. Cuando eran niños, se enfrentaron a una malévola criatura llamada "Eso" y hicieron una promesa olvidada relacionada con esto. La historia entrelaza sus experiencias como niños y sus vidas posteriores como adultos, ya que son atraídos de nuevo a Derry para enfrentar el mal que una vez los atormentó. Es una historia de horror y del paso de la niñez a la adultez, así como del poder de la memoria y las consecuencias del pasado que regresan para atormentar a los personajes en sus vidas adultas. ',
     image: Libro15,
     Author: 'Stephen King',
     Codigo: '978-84-34-34512-0',
     Disponibles: 6,
     Prestados: 3,
     Total: 9,
     year: '30 ago 1981',
     categoria: 'suspenso',
     valoracion: 3.5,
   },
   {
     id: 16,
     Titulo: 'The Non-Fiction',
     description:
       '"La Canción de Susannah" es la penúltima entrega de la serie de siete volúmenes de Stephen King, "La Torre Oscura". En esta novela, Mia, una madre demonio, se apodera del cuerpo de Susannah Dean y viaja a Nueva York en 1999, llevando consigo un misterioso "hijo". Mientras tanto, Roland y Eddie se encuentran en una realidad alterna en 1977, y se topan con el autor de una novela llamada "El Misterio de Salem". La historia se desarrolla con giros inesperados y un suspenso creciente, mientras los personajes buscan salvar la Torre Oscura y desvelan secretos sobre sus orígenes y propósitos. La trama se centra en la lucha por la supervivencia y la resolución de conflictos tanto en el mundo real como en mundos alternos, y se prepara para el emocionante clímax final de la serie.',
     image: Libro16,
     Author: 'Stephen King',
     Codigo: '123429199',
     Disponibles: 7,
     Prestados: 2,
     Total: 9,
     year: '30 ago 1980',
     categoria: 'suspenso',
     valoracion: 2.5,
   },
   {
     id: 17,
     Titulo: 'Song of Susannah',
     description:
       '"La Tormenta del Siglo" es una historia escrita por Stephen King específicamente para la televisión. La trama se desarrolla en Little Tall Island, donde una tormenta feroz, llamada la Tormenta del Siglo, se desata, trayendo consigo algo aún más aterrador que el clima extremo. Un extraño llamado Andre Linoge llega a la isla y, tras cometer un acto violento, ofrece un trato inquietante a los residentes: si le dan lo que quiere, se marchará. La historia se centra en el conflicto y la tensión que se desencadena entre los habitantes de la isla mientras luchan por enfrentar este oscuro visitante y sus siniestras demandas en medio de la tormenta.La trama es una mezcla de elementos sobrenaturales y psicológicos que mantienen a los personajes y a los lectores en vilo. La novela plantea cuestiones sobre la naturaleza humana y cómo las personas reaccionan bajo presión, todo mientras se enfrentan a un enigmático villano.',
     image: Libro17,
     Author: 'Stephen King',
     Codigo: '978-84-111-6979-2',
     Disponibles: 5,
     Prestados: 1,
     Total: 6,
     year: '27 sep 1990',
     categoria: 'accion',
     valoracion: 1.5,
   },
   {
    id: 18,
     Titulo: 'La Tormenta del Siglo',
     description:
       'La trama se desarrolla en Little Tall Island, donde una tormenta feroz, llamada la Tormenta del Siglo, se desata, trayendo consigo algo aún más aterrador que el clima extremo. Un extraño llamado Andre Linoge llega a la isla y, tras cometer un acto violento, ofrece un trato inquietante a los residentes: si le dan lo que quiere, se marchará. La historia se centra en el conflicto y la tensión que se desencadena entre los habitantes de la isla mientras luchan por enfrentar este oscuro visitante y sus siniestras demandas en medio de la tormenta. La trama es una mezcla de elementos sobrenaturales y psicológicos que mantienen a los personajes y a los lectores en vilo. La novela plantea cuestiones sobre la naturaleza humana y cómo las personas reaccionan bajo presión, todo mientras se enfrentan a un enigmático villano. ',
     image: Libro18,
     Author: 'Stephen King',
     Codigo: '978-84-08-98126-0',
     Disponibles: 10,
     Prestados: 0,
     Total: 10,
     year: '20 sep 1504',
     categoria: 'drama',
     valoracion: 5,
   },
   {
     id: 19,
     Titulo: 'El resplandor',
     description:
       'Esta obra maestra del terror moderno llega implacablemente a un clímax absolutamente escalofriante y espeluznante, cuando los poderes psíquicos de un niño revelan el mal que acecha en un viejo hotel.',
     image: Libro19,
     Author: 'Stephen King',
     Codigo: '111-84-270-2790-0',
     Disponibles: 2,
     Prestados: 8,
     Total: 10,
     year: '13 sep 1640',
     categoria: 'suspenso',
     valoracion: 4.5,
   },
   {
     id: 20,
     Titulo: 'La Torre Oscura',
     description:
       'el primer volumen de la épica serie de George R. R. Martin, es un relato de fantasía que presenta un mundo donde las estaciones duran décadas y los peligros se ciernen. El conflicto se centra en los Stark de Invernalia, una familia implacable, y en otros personajes que luchan por el poder en este mundo lleno de magia, traición y juegos políticos. La narrativa abarca desde paisajes de frío despiadado hasta reinos de abundancia, mientras los personajes se embarcan en travesías traicioneras y luchan por sobrevivir en un juego de tronos mortal.',
     image: Libro20,
     Author: 'Stephen King',
     Codigo: '724023432',
     Disponibles: 0,
     Prestados: 6,
     Total: 6,
     year: '30 ago 2269',
     categoria: 'drama',
     valoracion: 3,
   },
   {
     id: 21,
     Titulo: 'Juego de Tronos',
     description:
       'En 2014, tras liderar las mayores manifestaciones de protesta en la historia de Venezuela contra el régimen de Nicolas Maduro, el joven político Leopoldo López se vio enfrentado a la decisión más difícil de su vida: o abandonaba su país y seguía la lucha desde el extranjero, o permanecía en Caracas hasta que lo detuvieran. Debía elegir entre la libertad, o la cárcel. Decidió sacrificar su vida familiar y confortable —y entregarse. Al hacer lo que nadie esperaba, se convirtió en héroe.',
     image: Libro21,
     Author: 'George R.R. MARTIN',
     Codigo: '231-84-666-6977-8',
     Disponibles: 9,
     Prestados: 4,
     Total: 13,
     year: '20 sep 2023',
     categoria: 'drama',
     valoracion: 2,
     },
   {
     id: 22,
     Titulo: 'Deseos de Navidad',
     description:
       'Paris Reid no estaba dispuesta a conformarse con menos que lo mejor en lo que a hombres se refería. Pero el mejor era Will Bryson. Después de que su aventura terminara de forma desastrosa tres años atrás, Paris ni siquiera había mirado a otro hombre. Ahora, encerrados en un remoto hotel bajo vigilancia policial, Will y Paris estaban destinados a pasar juntos la Navidad. Les perseguía un asesino fugado, un hombre al que habían ayudado a condenar. Las cosas parecían bastante sombrías... pero Paris sabía exactamente lo que quería para Navidad. Sólo era cuestión de saber si lo conseguiría.',
     image: Libro22,
     Author: 'Sally Wentworth',
     Codigo: '978-84-1267-329-5',
     Disponibles: 6,
     Prestados: 4,
     Total: 10,
     year: '30 ene 2023',
     categoria: 'romance',
     valoracion: 3.5,
   },
   {
     id: 23,
     Titulo: 'Desire',
     description:
       'Jessica Sheldon y Steve Donovan estaban emparentados por matrimonio -la madre de ella y el padre de él- y, sin embargo, no compartían nada excepto la antipatía mutua. El hombre era guapísimo... ¡pero totalmente insufrible! Jessica ansiaba borrar esa exasperante sonrisa de sabelotodo de la cara de Steve, sobre todo después de que las circunstancias los unieran en un viaje único en la vida.Jessica estaba convencida de que no quería ni necesitaba un acompañante "fraternal" en su misión en Australia... ni que la metieran de cabeza en la vida secreta de Steve como agente del gobierno. Su preciado autocontrol estaba fallando. ¿Era la emoción del peligro y la intriga... o la pasión ardiente que ya no podía negar?',
     image: Libro23,
     Author: 'Annette Broadrick',
     Codigo: '2213322335',
     Disponibles: 8,
     Prestados: 2,
     Total: '9',
     year: '20 sep 1983',
     categoria: 'romance',
     valoracion: 4.5,
   },
   {
     id: 24,
     Titulo: 'PASADO, PRESENTE... ¿FUTURO?',
     description:
       'Cuatro años atrás, el rudo Carson Blackridge había marcado a Lara con su toque masculino y luego había aplastado su inocente corazón. Totalmente humillada, había huido para siempre del Rocking B. A regañadientes regresaba, pero sólo para investigar la historia del rancho, no para revivir el hexagonal pasado con Carson.',
     image: Libro24,
     Author: 'SAnn Maxwell',
     Codigo: '0032331801',
     Disponibles: 6,
     Prestados: 3,
     Total: 9,
     year: '6 sep 2023',
     categoria: 'suspenso',
     valoracion: 2.5,
   },
    {
     id: 25,
     Titulo: '¿Una nueva vida, un nuevo amor?',
     description:
       'Susan Hardy dejó su ciudad natal en Australia para asegurarse un futuro mejor en Sydney. Y fue contratada, nada más verla, por un abogado deslumbrantemente atractivo. En poco tiempo se sintió abrumada y confusa por las atenciones de su nuevo jefe, y acudió a su buen amigo, un hombre que había conocido en el parque, en busca de consejo. Pero en lugar de tranquilizarla, Dave le advirtió que no se involucrara con el tipo de hombre equivocado, como si él supiera lo que realmente era mejor para ella...',
     image: Libro25,
     Author: 'Emma Darcy',
     Codigo: '111-84-000-6384-1',
     Disponibles: 6,
     Prestados: 3,
     Total: '9',
     year: '13 sep 1988',
     categoria: 'romance',
     valoracion: '4',
   },
   {
     id: 26,
     Titulo: 'Harry en Hogwarts',
     description:
       'Mientras existan hombres que no amen a las mujeres… Lisbeth Salander volverá. La nueva novela de la Serie Millennium, el fenómeno literario que ha atrapado a más de 105 millones de lectores, de la mano de Karin Smirnoff, autora revelación de la narrativa sueca. «Ningún escritor, salvo el mismísimo Stieg Larsson, podría haber escrito una novela así.',
     image: Libro26,
     Author: 'Joanne K. rowling',
     Codigo: '222-84-166-1234-2',
     Disponibles: 6,
     Prestados: 3,
     Total: 9,
     year: '15 ene 1999',
     categoria: 'accion',
     valoracion: 4,
   },
   {
     id: 27,
     Titulo: 'Dracula',
     description:
       'Conozca los primeros años de la vida de Stoker, su variopinta carrera y los famosos amigos que hizo hasta la creación de su obra magna, Drácula.Sintonice con las teorías especulativas sobre la vida personal de Stoker y sus tendencias homosexuales profundamente reprimidas. Profundice en el folclore y el misticismo que inspiraron Drácula, en la propia obra maestra y en el impacto duradero que sigue teniendo en la cultura pop. Esta introducción anotada que acompaña a esta novela clásica es esencial para todos los aficionados al Drácula de Bram Stoker. Te doy la bienvenida, lector, como el Conde Drácula hizo señas a Jonathan Harker: Bienvenido a mi casa. Entra libremente y a tu libre albedrío". ',
     image: Libro27,
     Author: 'Bram Stoker',
     Codigo: '978-84-08-11111-0',
     Disponibles: 6,
     Prestados: 3,
     Total: 9,
     year: '30 ago 1111',
     categoria: 'suspenso',
     valoracion: 3.5,
   },
   {
     id: 28,
     Titulo: 'Las Olas Del Tiempo Perdido',
     description:
       'Eran cómplices de aventuras. Como Los Cinco, esas novelas juveniles de unos amigos inseparables. Lo fueron hasta que un segundo lo cambió todo. Los veranos de la infancia, la vida sin prisas y aquella amistad que parecía eterna estalló en un coche una madrugada de invierno. El peso de la culpa dinamitó sus sueños y dejaron de verse. Pero la delirante promesa de celebrar juntos el cuarenta cumpleaños de un muerto volverá a reencontrarlos veintiún años después. Ha pasado demasiado tiempo. Se han convertido en desconocidos, pero todos deciden cumplir y pasar cuatro días juntos para redescubrirse y comprobar que más allá de la muerte, más allá del dolor, está la vida y esa amistad que les pertenece y ha dado valor a su supervivencia. ',
     image: Libro28,
     Author: 'Sandra Barneda',
     Codigo: '2222329199',
     Disponibles: 7,
     Prestados: 2,
     Total: 9,
     year: '16 sep 1123',
     categoria: 'romance',
     valoracion: 2.5,
   },
   {
     id: 29,
     Titulo: 'La Esposa Del Dios Del Fuego',
     description:
       'La vida siempre supera al mejor de los guiones una productora de series de televisión que está en un portal que está en una calle que está en uno de los mejores barrios de la ciudad… Por las páginas de Bocabesada aparecen un colaborador televisivo, autor de éxito en crisis; mujeres inteligentes presas de sus errores; puro amor en la tercera edad; directivos mediocres; gente que se muere; un ministro y una puta encantada de serlo.',
     image: Libro29,
     Author: 'Amy tan',
     Codigo: '111-84-670-0000-2',
     Disponibles: 5,
     Prestados: 1,
     Total: 6,
     year: '27 oct 1888',
     categoria: 'romance',
     valoracion: 1.5,
   },
   {
    id: 30,
     Titulo: 'Cortando El Aire',
     description:
       ' Lucía recibe la notificación de que su marido, Adolfo Costa, se encuentra en coma en un hospital de Barcelona tras permanecer cuatro años en paradero desconocido. Pese a que ella sufre de amnesia y no recuerda nada de su vida anterior, no tiene más remedio que hacerse cargo de la situación. El médico que lleva el caso, un neurólogo llamado Sergio Rivas, le informa del estado terminal del enfermo y de que este fue víctima de un extraño accidente (atropellado y abandonado sin documentación en la cuneta de una autopista). Desde entonces Adolfo, sumido en la inconsciencia y el anonimato, se ha ido consumiendo en el hospital hasta que un día es identificado casualmente por una misteriosa mujer de origen ruso. Este hecho originará una investigación policial, en la que Lucía sufrirá la persecución del subinspector Alarte, hombre rudo y resentido, que la acosará hasta obligarla a enfrentarse a su escabroso pasado. ',
     image: Libro30,
     Author: 'Pilar Laura mateo',
     Codigo: '978-84-69-11111-5',
     Disponibles: 10,
     Prestados: 0,
     Total: 10,
     year: '20 sep 1992',
     categoria: 'romance',
     valoracion: 5,
   },
   {
     id: 31,
     Titulo: 'Fin de los Tiempos',
     description:
       'El Fin de los Tiempos ha llegado. Archaon el Elegido marcha sobre Middenheim. Si conquista la ciudad, tendrá en sus manos la clave para la victoria definitiva de los dioses del Caos. Los últimos héroes de los humanos, de los elfos y de los enanos se unen para detenerlo, pero además deben recurrir a oscuros aliados para hacer frente a las hordas de los Poderes Ruinosos.Aunque parezca una locura, es posible que la última esperanza del mundo resida en el Rey Inmortal, el mismísimo Nagash… siempre y cuando haga causa común con las razas mortales y colabore con ellas. De lo contrario, el plan de Archaon tendrá éxito y el Caos consumirá el mundo. He aquí un relato del fin del mundo tal y como lo conocemos. Una mirada sombría y trágica, completamente épica y entretenida de los últimos días del mundo de Warhammer y los héroes y villanos que lucharon para salvarlo o condenarlo.',
     image: Libro31,
     Author: 'Josh Reynolds',
     Codigo: '111-84-000-5143-0',
     Disponibles: 2,
     Prestados: 8,
     Total: 10,
     year: '13 sep 1666',
     categoria: 'romance',
     valoracion: 4.5,
   },
   {
     id: 32,
     Titulo: 'Nigromante',
     description:
       'Entrerríos se está convirtiendo en una aldea inhabitable. Las cosechas son peores cada año, la caza escasea, la tierra está enfermando y pudriéndose, e incluso están empezando a aparecer muertos vivientes. Sus habitantes lo saben pero temen decirlo: un nigromante se ha asentado en La Entraña, al otro lado de las montañas, y está poniendo en peligro sus vidas. El hijo de Miles, jefe de la aldea, acaba de desaparecer, y un grupo de granjeros armados con poco más que cuchillos y martillos decidirán salir en busca del nigromante. Los granjeros se enfrentarán a un mal que apenas pueden comprender y mayor de lo que serían capaces de imaginar. De la energía mágica de la bruja Neana dependerá que puedan avanzar en su travesía.',
     image: Libro32,
     Author: 'Carlos sisi',
     Codigo: '111117896',
     Disponibles: 0,
     Prestados: 6,
     Total: 6,
     year: '30 ago 1987',
     categoria: 'suspenso',
     valoracion: 3,
   },
   {
     id: 33,
     Titulo: 'Pesadilla antes de Navidad',
     description:
       'Jack Skelleton es el rey de ciudad de Halloween; sin embargo, tras muchos años haciendo una y otra vez lo mismo, se ha aburrido de asustar. Un día, de forma accidental, Jack descubre la ciudad de la Navidad, y es entonces cuando concibe un plan para apoderarse de las navidades. ¿Será capaz alguien como Jack, acostumbrado a Halloween y a los sustos, difundir la alegría navideña como nuevo Santa Claus?',
     image: Libro33,
     Author: 'Disney',
     Codigo: '0010330251',
     Disponibles: 9,
     Prestados: 4,
     Total: 13,
     year: '4 oct 2023',
     categoria: 'accion',
     valoracion: 2,
     },
   {
     id: 34,
     Titulo: 'Larga vida a la reina de Halloween',
     description:
       'Sally Skelleton es la nueva reina de Halloween tras un breve noviazgo con su amor verdadero, Jack Skelleton, a quien Sally adora con cada centímetro de costura de su piel. Ojalá pudiera decir lo mismo de su nuevo rol como reina. En el punto de mira y abrumada por todas las tareas reales que tiene que cumplir, Sally no puede evitar preguntarse si no habrá cambiado su vida de servidumbre junto al doctor Finkelstein por otro tipo de jaula. Cuando Sally y Zero descubren por accidente una puerta secreta que conduce a la ciudad del Sueño, desencadenan sin saberlo una serie de siniestros acontecimientos que pondrán en peligro su futuro como reina y el de toda la ciudad de Halloween.¿Podrá Sally descubrir lo que significa ser fiel a sí misma y salvar su hogar? ¿O se convertirá su futuro en una verdadera pesadilla?',
     image: Libro34,
     Author: 'Disney',
     Codigo: '90010330252',
     Disponibles: 6,
     Prestados: 4,
     Total: 10,
     year: '4 oct 2023',
     categoria: 'romance',
     valoracion: 3.5,
   },
   {
     id: 35,
     Titulo: 'El espacio',
     description:
       'En 2014, tras liderar las mayores manifestaciones de protesta en la historia de Venezuela contra el régimen de Nicolas Maduro, el joven político Leopoldo López se vio enfrentado a la decisión más difícil de su vida: o abandonaba su país y seguía la lucha desde el extranjero, o permanecía en Caracas hasta que lo detuvieran. Debía elegir entre la libertad, o la cárcel. Decidió sacrificar su vida familiar y confortable —y entregarse. Al hacer lo que nadie esperaba, se convirtió en héroe.',
     image: Libro35,
     Author: 'YOYO',
     Codigo: '0010324740',
     Disponibles: 8,
     Prestados: 2,
     Total: '9',
     year: '4 oct 2023',
     categoria: 'accion',
     valoracion: 4.5,
   },
   {
     id: 36,
     Titulo: 'Conjuro de noche y estrellas',
     description:
       'Seis meses después de finalizar las pruebas Aren, Cordelia y Blue han seguido con sus vidas cargando el peso de la pérdida de Wynd.  Aren debe encontrar a una misteriosa asesina que está dando muerte a los consejeros del Deirnas y llevarla ante su padre. Pero esta, a quien Aren ha apodado Moonlight, acaba convirtiéndose en algo más que una misión que cumplir. Cordelia ha encontrado información confidencial que la llevará a cuestionarse todo en lo que ha creído siempre y que puede conducirla por un camino muy peligroso y sin retorno. Y en esa búsqueda que puede hacer que los cimientos de los sidh se tambaleen, Blue jugará un papel inesperado.Una guerra se acerca, y el pasado y el presente colisionan revelando secretos ocultos que determinarán el futuro de todos. ',
     image: Libro36,
     Author: 'Nerea Llanes',
     Codigo: '0010331295',
     Disponibles: 6,
     Prestados: 3,
     Total: 9,
     year: '4 oct 2023',
     categoria: 'romance',
     valoracion: 2.5,
   },
   {
     id: 37,
     Titulo: 'Éxtasis',
     description:
       'El gran desenlace de la Serie Crave. Ya forma parte de ti.Han pasado tres meses desde que mis amigos y yo derrotamos a Cyrus. Tres meses en los que mi mayor temor ha sido lo que vendrá después… Debería haber sabido que esto era demasiado bueno para durar, y ahora todo se está rompiendo en mil pedazos.No me queda otra opción que volver al Reino de las Sombras y enfrentarme a la terrible reina que casi acaba con todos nosotros. Debo hacer un pacto con ella para salvar a Mekhi, pero esta vez me llevaré a mis poderosos amigos conmigo, y también a Hudson, aunque siento que le pasa algo raro; nos está ocultando un secreto, incluso a mí.Lo único que sé es que nuestras vidas corren peligro, y todo es culpa mía porque aún le debo un favor a la Anciana… y claramente ha venido a buscarlo.',
     image: Libro37,
     Author: 'Tracy Wolff',
     Codigo: '0010331352',
     Disponibles: 6,
     Prestados: 3,
     Total: '9',
     year: '4 oct 2023',
     categoria: 'romance',
     valoracion: '4',
   },
   {
     id: 38,
     Titulo: 'Kylewood Academy',
     description:
       '¡Bienvenidos a Kylewood Academy!La vida de Sophie comienza a tambalearse cuando su padre decide casarse con una desconocida y enviarla a un internado elitista que retrasará su entrada en la universidad.Puede que para el resto del mundo estudiar tras los muros de Kylewood Academy sea un sueño, pero para ella es una pesadilla de la que solo desea despertar. No tiene intención de dejarse seducir por los impresionantes edificios victorianos ni por sus jardines de colores imposibles.',
     image: Libro38,
     Author: 'Duna Alba',
     Codigo: '0010328901',
     Disponibles: 6,
     Prestados: 3,
     Total: 9,
     year: '4 oct 2023',
     categoria: 'drama',
     valoracion: 4,
   },
   {
     id: 39,
     Titulo: 'Still with us',
     description:
       'No podrás resistirte al esperado desenlace de Still with you y Still with me Tras recibir una llamada denunciando unos ruidos molestos, el oficial Lee Minki y su compañero de rondas, Jong Sungguk, acuden a inspeccionar un vecindario de clase media ubicado en la ciudad de Daegu, Corea del Sur.Una vez allí, no encuentran más que un rastro de sangre junto a un chico que no sabe explicar dónde se encuentra su pareja. Ha ocurrido un secuestro y todo parece apuntar a que Lee Minki podría ser el siguiente.',
     image: Libro39,
     Author: 'Lily del Pilar',
     Codigo: '0010328597',
     Disponibles: 6,
     Prestados: 3,
     Total: 9,
     year: '20 sep 2023',
     categoria: 'accion',
     valoracion: 3.5,
   },
   {
     id: 40,
     Titulo: 'Nadie dijo que fuera fácil',
     description:
       '"Abby lleva años enamorada de Dylan, el hermano de su mejor amiga Liv. Pero siempre ha sido un amor platónico, pues él es diez años mayor, vive en California y ni siquiera repara en su existencia.Tras verse plantado prácticamente en el altar por la que creía el amor de su vida, Dylan ha regresado a casa para curarse las heridas. La misma casa donde Abby pasa un mes todos los veranos desde que él se fue. Solo que, ahora, a sus casi veintidós años, Abby se ha convertido en una mujer alocada, desinhibida y… muy atractiva, que no va a dejar pasar la oportunidad de conquistar el corazón de Dylan.',
     image: Libro40,
     Author: 'Zuleima Esteve',
     Codigo: '0010324797',
     Disponibles: 7,
     Prestados: 2,
     Total: 9,
     year: '20 sep 2023',
     categoria: 'drama',
     valoracion: 2.5,
   },
 
 ];
 